apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus-nifi
  name: nifi-exporter
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    port: nifi-metrics
    interval: 15s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
      - nifi
  selector:
    matchLabels:
      app: exporter
