apiVersion: v1
kind: Service
metadata:
  name: nifi-exporter-service
  namespace: nifi
  labels:
    app: exporter
spec:
  type: ClusterIP
  ports:
    - name: nifi-metrics
      port: 8000  
      targetPort: 8000  
      protocol: TCP
  selector:
    app: exporter 