{
 "title": "Kafka 11",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Infor Kafka Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of broker ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_brokers{namespace=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "description": "Partitions that are online",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{namespace=\"kafka\"})"
    }
   ]
  },
  {
   "title": "## Infor Broker",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "kafka_broker_info{namespace=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kafka Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "## Total Message per Topic",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 20, "x": 1, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, max by(topic) (kafka_log_log_logendoffset{namespace=\"kafka\", topic!=\"__consumer_offsets\"}))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "## Total Message push into Topic",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 20, "x": 1, "y": 20 },
   "targets": [
    {
     "expr": "kafka_consumergroup_current_offset_sum{namespace=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "## Total Message",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 1, "y": 28 },
   "targets": [
    {
     "expr": "kafka_consumergroup_current_offset_sum{namespace=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of times push message (by topic)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_totalproducerequestspersec_count{namespace=\"kafka\", topic!=\"\", topic!=\"__consumer_offsets\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Kafka Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Consumer Lag per Topic",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 2, "y": 46 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag_sum{namespace=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer lag by group",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 53 },
   "targets": [
    {
     "expr": "max by(topic) (kafka_consumergroup_current_offset_sum{namespace=\"kafka\"})",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true
  },
  { "title": "Infor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } }
 ]
}