{
 "title": "Kafka 11",
 "time": { "from": "now-5d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Topic",
    "label": "Topic",
    "query": {
     "query": "label_values({namespace=\"kafka\"},topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of broker ",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,kafka_controller_kafkacontroller_activebrokercount{namespace=\"kafka\"})",
     "legendFormat": "Broker Count"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{namespace=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{namespace=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "description": "Partitions that are online",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{namespace=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Log size per Topic/ Byte",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 20, "x": 1, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sum(kafka_log_log_size{namespace=\"kafka\", topic!=\"__consumer_offsets\" }) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Number of times push message (by topic)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 22, "x": 1, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_totalproducerequests_total{namespace=\"kafka\", topic!=\"\" , topic !=\"__consumer_offsets\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Change pushed Message per Days",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{namespace=\"kafka\", topic!=\"\", topic=\"$Topic\"} ",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{namespace=\"kafka\", topic!=\"\", topic=\"$Topic\"} ",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}