{
 "title": "Kafka 27",
 "time": { "from": "now-5d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Topic",
    "label": "Topic",
    "query": {
     "query": "label_values({namespace=\"kafka\"},topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "New panel",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{namespace=\"kafka\" ,  topic=\"$Topic\" }",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of broker ",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,kafka_controller_kafkacontroller_activebrokercount{namespace=\"kafka\"})",
     "legendFormat": "Broker Count"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{namespace=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{namespace=~\"kafka\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "description": "Partitions that are online",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{namespace=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Log size per Topic/ Byte",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 20, "x": 1, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(kafka_log_log_size{namespace=\"kafka\", topic!=\"__consumer_offsets\" }) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "## All Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"kafka\" , topic!=\"\", topic!=\"__consumer_offsets\" , topic=\"$Topic\" }) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{namespace=\"kafka\", topic!=\"\", topic=\"$Topic\"} ",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}