{
 "title": "Nifi Log",
 "time": { "from": "now-5s", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "groupName", "label": "Group Name", "query": { "query": "label_values(group_name)" } }
  ]
 },
 "panels": [
  { "title": "Info Nifi Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "topk(1, nifi_address{namespace=\"nifi\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NiFi Active Thread Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_active_thread_count{namespace=\"nifi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_queued{namespace=\"nifi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_status{namespace=\"nifi\", status=\"DISCONNECTED\"} or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_status{namespace=\"nifi\" , status=\"CONNECTED\" }",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Info of Processor ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "## Total Processor Error ",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "nifi_status_processors_api{namespace=\"nifi\" , status=\"ERROR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nifi_status_processors_api{namespace=\"nifi\" , status=\"ERROR\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "## Processor Error by Group Name",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 4, "y": 20 },
   "targets": [
    {
     "expr": "nifi_status_processors_api{group_name=\"$groupName\" , status=\"ERROR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "## Total API Connect",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "nifi_status_invoke_api{namespace=\"nifi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nifi_status_invoke_api{namespace=\"nifi\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "##  API Connect by Group Name",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 3, "y": 36 },
   "targets": [
    {
     "expr": "nifi_status_invoke_api{group_name=\"$groupName\", namespace=\"nifi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "## Total API Connect",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "nifi_status_kafka_connect{namespace=\"nifi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nifi_status_kafka_connect{namespace=\"nifi\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}