{
 "title": "Nifi Log lele",
 "time": { "from": "now-5s", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "groupName",
    "label": "groupName",
    "query": {
     "query": "label_values({namespace=\"nifi\"},group_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Info Nifi Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "topk(1, nifi_address{namespace=\"nifi\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Connected",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_status{namespace=\"nifi\" , status=\"CONNECTED\" }",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Disconnected",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_status{namespace=\"nifi\", status=\"DISCONNECTED\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_queued{namespace=\"nifi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_active_thread_count{namespace=\"nifi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Info Group Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "## Count Processor Error",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_error_count{namespace=\"nifi\", group_name=\"$groupName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "## Count Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_running_count{namespace=\"nifi\", group_name=\"$groupName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "## Count Stopped",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_stopped_count{namespace=\"nifi\", group_name=\"$groupName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "## Count Invalid ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_invalid_count{namespace=\"nifi\", group_name=\"$groupName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Info of Detail Processor ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "## Total Processor Error ",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 3, "y": 21 },
   "targets": [
    {
     "expr": "nifi_status_processors_api_total{namespace=\"nifi\", status=\"ERROR\", group_name=\"$groupName\", run_status=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "## Total Detail Error",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "nifi_status_processors_api_total{namespace=\"nifi\", status=\"ERROR\", group_name=\"$groupName\", run_status=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "## Total API Connect",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "nifi_status_invoke_api_total{namespace=\"nifi\", group_name=\"$groupName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "## Total Kafka Topic Connect",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "nifi_status_kafka_connect_created{namespace=\"nifi\", group_name=\"$groupName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nifi_status_kafka_connect_total{namespace=\"nifi\", group_name=\"$groupName\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}